# filebeat.yml
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
      - /var/log/syslog
      - /var/log/auth.log
      - /var/log/cron.log
      - /var/log/secure
    # If you want to ingest the SSH logs from /var/log/auth.log or /var/log/secure on some distributions.

# Also possible to watch the pcap (but that's not typically "parsed" in ELK):
#   - /var/log/packets.pcap

output.logstash:
  hosts: ["logstash:5044"]
  # if you require SSL or anything, configure it here

# If you want to do modules, etc., you can enable them like so:
# filebeat.modules:
#   - module: system
#     syslog:
#       enabled: true
#     auth:
#       enabled: true
